# Generated by Django 4.2.6 on 2024-01-11 22:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('endDate', models.DateField(default=datetime.datetime(2024, 1, 12, 22, 6, 37, 67545, tzinfo=datetime.timezone.utc), verbose_name='End Date')),
            ],
        ),
    ]
