# Generated by Django 4.2.6 on 2024-01-15 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 20, 16, 14, 369760, tzinfo=datetime.timezone.utc), verbose_name='End Date'),
        ),
    ]
